// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VolunteerHub.Data;

#nullable disable

namespace VolunteerHub.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("VolunteerHub.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("VolunteerHub.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId", "Name")
                        .IsUnique();

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Athens"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "Thessaloniki"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            Name = "Patras"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 1,
                            Name = "Heraklion"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 1,
                            Name = "Larissa"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 1,
                            Name = "Volos"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 1,
                            Name = "Ioannina"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 1,
                            Name = "Kavala"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 1,
                            Name = "Kalamata"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 1,
                            Name = "Serres"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 2,
                            Name = "Zurich"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 2,
                            Name = "Geneva"
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 2,
                            Name = "Basel"
                        },
                        new
                        {
                            Id = 14,
                            CountryId = 2,
                            Name = "Bern"
                        },
                        new
                        {
                            Id = 15,
                            CountryId = 2,
                            Name = "Lausanne"
                        },
                        new
                        {
                            Id = 16,
                            CountryId = 2,
                            Name = "Lucerne"
                        },
                        new
                        {
                            Id = 17,
                            CountryId = 2,
                            Name = "Winterthur"
                        },
                        new
                        {
                            Id = 18,
                            CountryId = 2,
                            Name = "St. Gallen"
                        },
                        new
                        {
                            Id = 19,
                            CountryId = 2,
                            Name = "Zug"
                        },
                        new
                        {
                            Id = 20,
                            CountryId = 2,
                            Name = "Lugano"
                        },
                        new
                        {
                            Id = 21,
                            CountryId = 3,
                            Name = "Berlin"
                        },
                        new
                        {
                            Id = 22,
                            CountryId = 3,
                            Name = "Hamburg"
                        },
                        new
                        {
                            Id = 23,
                            CountryId = 3,
                            Name = "Munich"
                        },
                        new
                        {
                            Id = 24,
                            CountryId = 3,
                            Name = "Cologne"
                        },
                        new
                        {
                            Id = 25,
                            CountryId = 3,
                            Name = "Frankfurt"
                        },
                        new
                        {
                            Id = 26,
                            CountryId = 3,
                            Name = "Stuttgart"
                        },
                        new
                        {
                            Id = 27,
                            CountryId = 4,
                            Name = "Vienna"
                        },
                        new
                        {
                            Id = 28,
                            CountryId = 4,
                            Name = "Graz"
                        },
                        new
                        {
                            Id = 29,
                            CountryId = 4,
                            Name = "Linz"
                        },
                        new
                        {
                            Id = 30,
                            CountryId = 4,
                            Name = "Salzburg"
                        },
                        new
                        {
                            Id = 31,
                            CountryId = 4,
                            Name = "Innsbruck"
                        },
                        new
                        {
                            Id = 32,
                            CountryId = 5,
                            Name = "Paris"
                        },
                        new
                        {
                            Id = 33,
                            CountryId = 5,
                            Name = "Marseille"
                        },
                        new
                        {
                            Id = 34,
                            CountryId = 5,
                            Name = "Lyon"
                        },
                        new
                        {
                            Id = 35,
                            CountryId = 5,
                            Name = "Toulouse"
                        },
                        new
                        {
                            Id = 36,
                            CountryId = 5,
                            Name = "Nice"
                        },
                        new
                        {
                            Id = 37,
                            CountryId = 6,
                            Name = "Rome"
                        },
                        new
                        {
                            Id = 38,
                            CountryId = 6,
                            Name = "Milan"
                        },
                        new
                        {
                            Id = 39,
                            CountryId = 6,
                            Name = "Naples"
                        },
                        new
                        {
                            Id = 40,
                            CountryId = 6,
                            Name = "Turin"
                        },
                        new
                        {
                            Id = 41,
                            CountryId = 6,
                            Name = "Florence"
                        },
                        new
                        {
                            Id = 42,
                            CountryId = 7,
                            Name = "Madrid"
                        },
                        new
                        {
                            Id = 43,
                            CountryId = 7,
                            Name = "Barcelona"
                        },
                        new
                        {
                            Id = 44,
                            CountryId = 7,
                            Name = "Valencia"
                        },
                        new
                        {
                            Id = 45,
                            CountryId = 7,
                            Name = "Seville"
                        },
                        new
                        {
                            Id = 46,
                            CountryId = 7,
                            Name = "Malaga"
                        },
                        new
                        {
                            Id = 47,
                            CountryId = 8,
                            Name = "Amsterdam"
                        },
                        new
                        {
                            Id = 48,
                            CountryId = 8,
                            Name = "Rotterdam"
                        },
                        new
                        {
                            Id = 49,
                            CountryId = 8,
                            Name = "The Hague"
                        },
                        new
                        {
                            Id = 50,
                            CountryId = 8,
                            Name = "Utrecht"
                        },
                        new
                        {
                            Id = 51,
                            CountryId = 9,
                            Name = "Brussels"
                        },
                        new
                        {
                            Id = 52,
                            CountryId = 9,
                            Name = "Antwerp"
                        },
                        new
                        {
                            Id = 53,
                            CountryId = 9,
                            Name = "Ghent"
                        },
                        new
                        {
                            Id = 54,
                            CountryId = 9,
                            Name = "Bruges"
                        },
                        new
                        {
                            Id = 55,
                            CountryId = 10,
                            Name = "London"
                        },
                        new
                        {
                            Id = 56,
                            CountryId = 10,
                            Name = "Manchester"
                        },
                        new
                        {
                            Id = 57,
                            CountryId = 10,
                            Name = "Birmingham"
                        },
                        new
                        {
                            Id = 58,
                            CountryId = 10,
                            Name = "Liverpool"
                        },
                        new
                        {
                            Id = 59,
                            CountryId = 10,
                            Name = "Edinburgh"
                        },
                        new
                        {
                            Id = 60,
                            CountryId = 10,
                            Name = "Glasgow"
                        });
                });

            modelBuilder.Entity("VolunteerHub.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "GR",
                            Name = "Greece",
                            TimeZoneId = "Europe/Athens"
                        },
                        new
                        {
                            Id = 2,
                            Code = "CH",
                            Name = "Switzerland",
                            TimeZoneId = "Europe/Zurich"
                        },
                        new
                        {
                            Id = 3,
                            Code = "DE",
                            Name = "Germany",
                            TimeZoneId = "Europe/Berlin"
                        },
                        new
                        {
                            Id = 4,
                            Code = "AT",
                            Name = "Austria",
                            TimeZoneId = "Europe/Vienna"
                        },
                        new
                        {
                            Id = 5,
                            Code = "FR",
                            Name = "France",
                            TimeZoneId = "Europe/Paris"
                        },
                        new
                        {
                            Id = 6,
                            Code = "IT",
                            Name = "Italy",
                            TimeZoneId = "Europe/Rome"
                        },
                        new
                        {
                            Id = 7,
                            Code = "ES",
                            Name = "Spain",
                            TimeZoneId = "Europe/Madrid"
                        },
                        new
                        {
                            Id = 8,
                            Code = "NL",
                            Name = "Netherlands",
                            TimeZoneId = "Europe/Amsterdam"
                        },
                        new
                        {
                            Id = 9,
                            Code = "BE",
                            Name = "Belgium",
                            TimeZoneId = "Europe/Brussels"
                        },
                        new
                        {
                            Id = 10,
                            Code = "GB",
                            Name = "United Kingdom",
                            TimeZoneId = "Europe/London"
                        });
                });

            modelBuilder.Entity("VolunteerHub.Models.ParticipationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Attended")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OrganizerNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("VolunteerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("ParticipationRequests");
                });

            modelBuilder.Entity("VolunteerHub.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxVolunteers")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RequiredSkill")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("VolunteerActionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VolunteerActionId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("VolunteerHub.Models.VolunteerAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ApplicationDeadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Instructions")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("MinimumAge")
                        .HasColumnType("int");

                    b.Property<string>("OrganizerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("OrganizerId");

                    b.ToTable("VolunteerActions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("VolunteerHub.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("VolunteerHub.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolunteerHub.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("VolunteerHub.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VolunteerHub.Models.ApplicationUser", b =>
                {
                    b.HasOne("VolunteerHub.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("City");
                });

            modelBuilder.Entity("VolunteerHub.Models.City", b =>
                {
                    b.HasOne("VolunteerHub.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("VolunteerHub.Models.ParticipationRequest", b =>
                {
                    b.HasOne("VolunteerHub.Models.Shift", "Shift")
                        .WithMany("ParticipationRequests")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolunteerHub.Models.ApplicationUser", "Volunteer")
                        .WithMany()
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Shift");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("VolunteerHub.Models.Shift", b =>
                {
                    b.HasOne("VolunteerHub.Models.VolunteerAction", "VolunteerAction")
                        .WithMany("Shifts")
                        .HasForeignKey("VolunteerActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VolunteerAction");
                });

            modelBuilder.Entity("VolunteerHub.Models.VolunteerAction", b =>
                {
                    b.HasOne("VolunteerHub.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VolunteerHub.Models.ApplicationUser", "Organizer")
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("VolunteerHub.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("VolunteerHub.Models.Shift", b =>
                {
                    b.Navigation("ParticipationRequests");
                });

            modelBuilder.Entity("VolunteerHub.Models.VolunteerAction", b =>
                {
                    b.Navigation("Shifts");
                });
#pragma warning restore 612, 618
        }
    }
}
